#!/usr/bin/env bash
# Bootstrap kuibysheff-1c-live: host checks, MCP tools, .env secrets, kbshff CLI provider.
set -euo pipefail

REPO_ROOT=""
TOOLS_DIR=""
SKIP_INGEST=0
NON_INTERACTIVE=0
BASE_URL=""
MODEL=""
API_KEY_ENV_NAME=""
PLATFORM_PATH=""

usage() {
  cat <<'EOF'
Usage: scripts/install.sh [--repo-root DIR] [--tools-dir DIR] [--skip-ingest]
                          [--non-interactive] [--base-url URL] [--model NAME]
                          [--api-key-env NAME] [--platform-path DIR]
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo-root) REPO_ROOT="$2"; shift 2 ;;
    --tools-dir) TOOLS_DIR="$2"; shift 2 ;;
    --skip-ingest) SKIP_INGEST=1; shift ;;
    --non-interactive) NON_INTERACTIVE=1; shift ;;
    --base-url) BASE_URL="$2"; shift 2 ;;
    --model) MODEL="$2"; shift 2 ;;
    --api-key-env) API_KEY_ENV_NAME="$2"; shift 2 ;;
    --platform-path) PLATFORM_PATH="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 2 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -z "$REPO_ROOT" ]]; then
  REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
else
  REPO_ROOT="$(cd "$REPO_ROOT" && pwd)"
fi
if [[ -z "$TOOLS_DIR" ]]; then
  TOOLS_DIR="$REPO_ROOT/tools"
fi

step() { echo "==> $*"; }
have() { command -v "$1" >/dev/null 2>&1; }

require_host() {
  local name="$1" hint="$2"
  if have "$name"; then
    echo "OK  $name"
    return
  fi
  echo "$name not found in PATH. $hint" >&2
  exit 1
}

dotenv_get() {
  local file="$1" key="$2"
  [[ -f "$file" ]] || return 0
  python3 - "$file" "$key" <<'PY'
import sys
path, key = sys.argv[1], sys.argv[2]
try:
    text = open(path, encoding="utf-8").read()
except FileNotFoundError:
    sys.exit(0)
for raw in text.splitlines():
    line = raw.strip()
    if not line or line.startswith("#") or "=" not in line:
        continue
    name, value = line.split("=", 1)
    name, value = name.strip(), value.strip()
    if len(value) >= 2 and ((value[0] == value[-1] == '"') or (value[0] == value[-1] == "'")):
        value = value[1:-1]
    if name == key:
        print(value)
        break
PY
}

# Keep a simple KEY=value file; last write wins for known keys via python.
dotenv_set_many() {
  local file="$1"
  local payload
  payload="$(cat)"
  UPDATES="$payload" python3 - "$file" <<'PY'
import os, sys
path = sys.argv[1]
existing = {}
order = []
if os.path.isfile(path):
    for raw in open(path, encoding="utf-8"):
        line = raw.rstrip("\n")
        if not line.strip() or line.lstrip().startswith("#") or "=" not in line:
            continue
        name, value = line.split("=", 1)
        name = name.strip()
        if name not in existing:
            order.append(name)
        existing[name] = value.strip()
preferred = [
    "KBSHFF_PROVIDER_BASE_URL",
    "KBSHFF_PROVIDER_MODEL",
    "KBSHFF_PROVIDER_API_KEY_ENV",
    "OPENAI_API_KEY",
    "POLZA_API_KEY",
    "DEEPSEEK_API_KEY",
    "SNTX_SEM_CONFIG",
    "SNTX_SEM_PYTHON",
    "BSL_INDEXER",
    "CODE_INDEX_HOME",
    "BSL_LS_MCP",
    "BSL_LS_JAR",
    "JAVA_HOME",
    "KBSHFF_BIN",
    "KUIBYSHEFF_SRC",
]
for raw in os.environ.get("UPDATES", "").splitlines():
    if "=" not in raw:
        continue
    k, v = raw.split("=", 1)
    existing[k] = v
    if k not in order:
        order.append(k)
lines = ["# Generated by scripts/install.sh. Secrets stay here, not in YAML or CLI argv."]
seen = set()
for k in preferred + order:
    if k in seen:
        continue
    if k not in existing or not existing[k]:
        continue
    lines.append(f"{k}={existing[k]}")
    seen.add(k)
with open(path, "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(lines) + "\n")
PY
}

read_default() {
  local prompt="$1" default="$2"
  if [[ "$NON_INTERACTIVE" -eq 1 ]]; then
    printf '%s' "$default"
    return
  fi
  local suffix="" value
  [[ -n "$default" ]] && suffix=" [$default]"
  read -r -p "${prompt}${suffix}: " value || true
  if [[ -z "$value" ]]; then
    printf '%s' "$default"
  else
    printf '%s' "$value"
  fi
}

read_secret() {
  local prompt="$1" value
  if [[ "$NON_INTERACTIVE" -eq 1 ]]; then
    printf ''
    return
  fi
  read -r -s -p "${prompt}: " value || true
  echo "" >&2
  printf '%s' "$value"
}

env_or_file() {
  local key="$1" file="$2"
  if [[ -n "${!key:-}" ]]; then
    printf '%s' "${!key}"
    return
  fi
  dotenv_get "$file" "$key"
}

github_asset_url() {
  local repo="$1" match="$2"
  python3 - "$repo" "$match" <<'PY'
import json, sys, urllib.request
repo, match = sys.argv[1], sys.argv[2]
req = urllib.request.Request(
    f"https://api.github.com/repos/{repo}/releases/latest",
    headers={"User-Agent": "kuibysheff-1c-live-install"},
)
with urllib.request.urlopen(req) as resp:
    data = json.load(resp)
for asset in data.get("assets", []):
    name = asset.get("name") or ""
    import fnmatch
    if fnmatch.fnmatch(name, match):
        print(asset["browser_download_url"])
        sys.exit(0)
raise SystemExit(f"No GitHub asset matching {match!r} in {repo}")
PY
}

find_under() {
  local root="$1" name="$2"
  find "$root" -type f -name "$name" 2>/dev/null | head -n 1
}

ensure_kbshff() {
  step "kbshff"
  local explicit src parent found release
  explicit="$(env_or_file KBSHFF_BIN "$ENV_FILE")"
  if [[ -n "$explicit" && -f "$explicit" ]]; then
    printf '%s' "$(cd "$(dirname "$explicit")" && pwd)/$(basename "$explicit")"
    return
  fi
  if have kbshff; then
    command -v kbshff
    return
  fi
  parent="$(cd "$REPO_ROOT/.." && pwd)"
  src="$(env_or_file KUIBYSHEFF_SRC "$ENV_FILE")"
  found=""
  for c in "$src" "$parent/Agent-Kuibysheff" "$parent/Agent Kuibyshev"; do
    [[ -n "$c" && -f "$c/Cargo.toml" ]] || continue
    found="$(cd "$c" && pwd)"
    break
  done
  if [[ -z "$found" ]]; then
    have git || { echo "kbshff not found and git is missing." >&2; exit 1; }
    have cargo || { echo "kbshff not found. Install cargo or set KBSHFF_BIN. https://github.com/gazalievtimur/Agent-Kuibysheff" >&2; exit 1; }
    found="$parent/Agent-Kuibysheff"
    echo "Cloning Agent-Kuibysheff -> $found"
    git clone --depth 1 https://github.com/gazalievtimur/Agent-Kuibysheff.git "$found"
  fi
  release="$found/target/release/kbshff"
  if [[ -f "$release" ]]; then
    printf '%s' "$release"
    return
  fi
  have cargo || { echo "cargo not found (needed to build kbshff from $found)" >&2; exit 1; }
  echo "Building kbshff from $found"
  (cd "$found" && cargo build --release -p agent_Kuibysheff --bin kbshff)
  [[ -f "$release" ]] || { echo "kbshff missing after cargo build" >&2; exit 1; }
  printf '%s' "$release"
}

indexer_asset_glob() {
  local u
  u="$(uname -s)"
  case "$u" in
    Linux) echo "bsl-indexer-linux-x64.tar.gz" ;;
    Darwin)
      if [[ "$(uname -m)" == "arm64" ]]; then
        echo "bsl-indexer-macos-arm64.tar.gz"
      else
        echo "bsl-indexer-macos-x64.tar.gz"
      fi
      ;;
    *) echo "bsl-indexer-linux-x64.tar.gz" ;;
  esac
}

ensure_indexer() {
  step "bsl-indexer"
  local existing rel dest url archive found stable
  for name in BSL_INDEXER CODE_INDEX_BIN BSL_INDEXER_EXE; do
    existing="$(env_or_file "$name" "$ENV_FILE")"
    if [[ -n "$existing" && -f "$existing" ]]; then
      printf '%s' "$(cd "$(dirname "$existing")" && pwd)/$(basename "$existing")"
      return
    fi
  done
  for rel in bsl-indexer code-index/bsl-indexer; do
    if [[ -f "$TOOLS_DIR/$rel" ]]; then
      printf '%s' "$(cd "$(dirname "$TOOLS_DIR/$rel")" && pwd)/$(basename "$TOOLS_DIR/$rel")"
      return
    fi
  done
  dest="$TOOLS_DIR/code-index"
  mkdir -p "$dest"
  url="$(github_asset_url Regsorm/code-index-mcp "$(indexer_asset_glob)")"
  archive="$(mktemp)"
  echo "Downloading $url"
  curl -fsSL -A "kuibysheff-1c-live-install" -o "$archive" "$url"
  tar -xzf "$archive" -C "$dest"
  rm -f "$archive"
  found="$(find_under "$dest" bsl-indexer)"
  [[ -n "$found" ]] || { echo "bsl-indexer not found after extract" >&2; exit 1; }
  stable="$TOOLS_DIR/bsl-indexer"
  cp "$found" "$stable"
  chmod +x "$stable"
  printf '%s' "$stable"
}

ensure_jar() {
  step "bsl-language-server JAR"
  local existing stable home_jar url
  existing="$(env_or_file BSL_LS_JAR "$ENV_FILE")"
  if [[ -n "$existing" && -f "$existing" ]]; then
    printf '%s' "$(cd "$(dirname "$existing")" && pwd)/$(basename "$existing")"
    return
  fi
  stable="$TOOLS_DIR/bsl-ls/bsl-language-server.jar"
  if [[ -f "$stable" ]]; then
    printf '%s' "$stable"
    return
  fi
  home_jar="${HOME}/.claude/bsl-ls/bsl-language-server.jar"
  mkdir -p "$(dirname "$stable")"
  if [[ -f "$home_jar" ]]; then
    cp "$home_jar" "$stable"
    printf '%s' "$stable"
    return
  fi
  url="$(github_asset_url 1c-syntax/bsl-language-server '*-exec.jar')"
  echo "Downloading $url"
  curl -fsSL -A "kuibysheff-1c-live-install" -o "$stable" "$url"
  printf '%s' "$stable"
}

ensure_mcp_js() {
  step "bsl-ls-mcp"
  local existing home_js vendor_js chosen
  existing="$(env_or_file BSL_LS_MCP "$ENV_FILE")"
  [[ -n "$existing" ]] || existing="$(env_or_file BSL_LS_SERVER "$ENV_FILE")"
  home_js="${HOME}/.claude/bsl-ls-mcp/server.js"
  vendor_js="$TOOLS_DIR/bsl-ls-mcp/server.js"
  if [[ -n "$existing" && -f "$existing" ]]; then
    chosen="$(cd "$(dirname "$existing")" && pwd)/$(basename "$existing")"
  elif [[ -f "$home_js" ]]; then
    chosen="$home_js"
  else
    chosen="$vendor_js"
  fi
  case "$chosen" in
    "$vendor_js"|*"${TOOLS_DIR}/bsl-ls-mcp"*)
      have npm || { echo "npm not found. Install Node.js: https://nodejs.org/" >&2; exit 1; }
      (cd "$TOOLS_DIR/bsl-ls-mcp" && npm install --omit=dev)
      chosen="$vendor_js"
      ;;
  esac
  printf '%s' "$chosen"
}

ensure_sntx() {
  step "1c-sntx-sem"
  local existing src parent venv_py config answer
  existing="$(env_or_file SNTX_SEM_CONFIG "$ENV_FILE")"
  src=""
  if [[ -n "$existing" && -f "$existing" ]]; then
    src="$(cd "$(dirname "$existing")" && pwd)"
  else
    parent="$(cd "$REPO_ROOT/.." && pwd)"
    for c in "$parent/1c-sntx-sem" "$TOOLS_DIR/1c-sntx-sem"; do
      if [[ -f "$c/pyproject.toml" ]]; then
        src="$(cd "$c" && pwd)"
        break
      fi
    done
  fi
  if [[ -z "$src" ]]; then
    have git || { echo "git not found (needed to clone 1c-sntx-sem)" >&2; exit 1; }
    src="$TOOLS_DIR/1c-sntx-sem"
    echo "Cloning 1c-sntx-sem -> $src"
    git clone --depth 1 https://github.com/gybson63/1c-sntx-sem.git "$src"
  fi
  venv_py="$src/.venv/bin/python"
  if [[ ! -x "$venv_py" ]]; then
    python3 -m venv "$src/.venv"
  fi
  "$venv_py" -m pip install -U pip
  (cd "$src" && "$venv_py" -m pip install -e .)
  config="$src/config.yaml"
  if [[ ! -f "$config" ]]; then
    [[ -f "$src/config.yaml.example" ]] || { echo "missing config.yaml.example" >&2; exit 1; }
    cp "$src/config.yaml.example" "$config"
    echo "Created $config from example — edit local_configs / ingest as needed."
  fi
  local do_ingest=1
  [[ "$SKIP_INGEST" -eq 1 ]] && do_ingest=0
  if [[ "$do_ingest" -eq 1 && "$NON_INTERACTIVE" -eq 0 ]]; then
    read -r -p "Run sntx_sem ingest from a 1C platform bin folder? [y/N] " answer || true
    [[ "$answer" =~ ^[Yy] ]] || do_ingest=0
  fi
  if [[ "$do_ingest" -eq 1 ]]; then
    if [[ -z "$PLATFORM_PATH" && "$NON_INTERACTIVE" -eq 0 ]]; then
      PLATFORM_PATH="$(read_default "Path to 1C platform bin" "")"
    fi
    if [[ -z "$PLATFORM_PATH" ]]; then
      echo "Skipping ingest: no platform path." >&2
    else
      (cd "$src" && "$venv_py" -m sntx_sem ingest --platform-path "$PLATFORM_PATH")
    fi
  else
    echo "Skipping ingest. Run ingest before a live eval if the index is empty." >&2
  fi
  printf '%s\n%s\n' "$config" "$venv_py"
}

resolve_java_home() {
  local existing
  existing="$(env_or_file JAVA_HOME "$ENV_FILE")"
  if [[ -n "$existing" && -d "$existing" ]]; then
    printf '%s' "$existing"
    return
  fi
  have java || { echo "java not found. Install JDK 17+: https://adoptium.net/" >&2; exit 1; }
  java -XshowSettings:properties -version 2>&1 | awk -F'= ' '/java.home/ {print $2; exit}'
}

apply_provider() {
  local kbshff="$1" project="$2" agent="$3" base="$4" model="$5" keyenv="$6"
  local staging settings name
  step "kbshff CLI: init / import / provider set / check ($agent)"
  mkdir -p "$project"
  "$kbshff" init "$agent" --project-root "$project" --force
  staging="$project/.kuibysheff/.1c-live-import/$agent"
  rm -rf "$staging"
  mkdir -p "$staging"
  settings="$REPO_ROOT/profiles/$agent"
  for name in master_prompt.md skills.dsl rules.md; do
    [[ -f "$settings/$name" ]] && cp "$settings/$name" "$staging/$name"
  done
  "$kbshff" config --project-root "$project" --agent "$agent" import --from "$staging" --force
  "$kbshff" config --project-root "$project" --agent "$agent" provider set \
    --base-url "$base" --model "$model" --api-key-env "$keyenv"
  "$kbshff" check --project-root "$project" --agent "$agent" --skip-mcp --skip-sandbox
}

ENV_FILE="$REPO_ROOT/.env"
mkdir -p "$TOOLS_DIR"

step "Host tools"
require_host oscript "Install OneScript 2.0: https://oscript.io/"
require_host git "https://git-scm.com/"
require_host node "https://nodejs.org/"
require_host java "JDK 17+: https://adoptium.net/"
require_host python3 "Python 3 is required for 1c-sntx-sem"
require_host curl "curl is required to download GitHub releases"

step "AI provider (CLI will apply these; key stays in .env)"
if [[ -z "$BASE_URL" ]]; then
  BASE_URL="$(env_or_file KBSHFF_PROVIDER_BASE_URL "$ENV_FILE")"
  [[ -n "$BASE_URL" ]] || BASE_URL="https://api.openai.com/v1"
  BASE_URL="$(read_default "Provider base_url" "$BASE_URL")"
fi
if [[ -z "$MODEL" ]]; then
  MODEL="$(env_or_file KBSHFF_PROVIDER_MODEL "$ENV_FILE")"
  [[ -n "$MODEL" ]] || MODEL="gpt-4o"
  MODEL="$(read_default "Model" "$MODEL")"
fi
if [[ -z "$API_KEY_ENV_NAME" ]]; then
  API_KEY_ENV_NAME="$(env_or_file KBSHFF_PROVIDER_API_KEY_ENV "$ENV_FILE")"
  [[ -n "$API_KEY_ENV_NAME" ]] || API_KEY_ENV_NAME="OPENAI_API_KEY"
  API_KEY_ENV_NAME="$(read_default "API key env var name" "$API_KEY_ENV_NAME")"
fi
API_KEY="$(env_or_file "$API_KEY_ENV_NAME" "$ENV_FILE")"
if [[ -z "$API_KEY" ]]; then
  API_KEY="$(read_secret "Value for ${API_KEY_ENV_NAME} (not echoed, not passed to CLI argv)")"
fi
if [[ -z "$API_KEY" ]]; then
  echo "API key for $API_KEY_ENV_NAME is required" >&2
  exit 1
fi
export "$API_KEY_ENV_NAME=$API_KEY"

KBSHFF_BIN="$(ensure_kbshff)"
BSL_INDEXER="$(ensure_indexer)"
BSL_LS_JAR="$(ensure_jar)"
BSL_LS_MCP="$(ensure_mcp_js)"
SNTX_OUT="$(ensure_sntx)"
SNTX_SEM_CONFIG="$(printf '%s\n' "$SNTX_OUT" | sed -n '1p')"
SNTX_SEM_PYTHON="$(printf '%s\n' "$SNTX_OUT" | sed -n '2p')"
JAVA_HOME_VAL="$(resolve_java_home || true)"

{
  echo "KBSHFF_PROVIDER_BASE_URL=$BASE_URL"
  echo "KBSHFF_PROVIDER_MODEL=$MODEL"
  echo "KBSHFF_PROVIDER_API_KEY_ENV=$API_KEY_ENV_NAME"
  echo "${API_KEY_ENV_NAME}=$API_KEY"
  echo "SNTX_SEM_CONFIG=$SNTX_SEM_CONFIG"
  echo "SNTX_SEM_PYTHON=$SNTX_SEM_PYTHON"
  echo "BSL_INDEXER=$BSL_INDEXER"
  echo "CODE_INDEX_HOME=$(dirname "$BSL_INDEXER")"
  echo "BSL_LS_MCP=$BSL_LS_MCP"
  echo "BSL_LS_JAR=$BSL_LS_JAR"
  echo "KBSHFF_BIN=$KBSHFF_BIN"
  [[ -n "$JAVA_HOME_VAL" ]] && echo "JAVA_HOME=$JAVA_HOME_VAL"
} | dotenv_set_many "$ENV_FILE"

export KBSHFF_PROVIDER_BASE_URL="$BASE_URL"
export KBSHFF_PROVIDER_MODEL="$MODEL"
export KBSHFF_PROVIDER_API_KEY_ENV="$API_KEY_ENV_NAME"
export SNTX_SEM_CONFIG BSL_INDEXER BSL_LS_MCP BSL_LS_JAR KBSHFF_BIN SNTX_SEM_PYTHON
[[ -n "$JAVA_HOME_VAL" ]] && export JAVA_HOME="$JAVA_HOME_VAL"
echo "Wrote $ENV_FILE"

apply_provider "$KBSHFF_BIN" "$TOOLS_DIR/.kbshff-install" "1c-analyst" "$BASE_URL" "$MODEL" "$API_KEY_ENV_NAME"

step "harness dry-run"
oscript -encoding=utf-8 "$REPO_ROOT/harness/run.os" --repo-root "$REPO_ROOT" --dry-run

echo ""
echo "Install OK."
echo "Provider was applied with:"
echo "  kbshff config --project-root <DIR> --agent <ID> provider set --base-url ... --model ... --api-key-env $API_KEY_ENV_NAME"
echo "Live eval:  ./harness/run.sh"
echo "Howto:      docs/howto-pipeline.md"
echo "CLI help:   kbshff help config"
