#Requires -Version 5.1
<#
.SYNOPSIS
  Bootstrap kuibysheff-1c-live: host checks, MCP tools, .env secrets, kbshff CLI provider.
#>
param(
    [string]$RepoRoot = "",
    [string]$ToolsDir = "",
    [switch]$SkipIngest,
    [switch]$NonInteractive,
    [string]$BaseUrl = "",
    [string]$Model = "",
    [string]$ApiKeyEnvName = "",
    [string]$PlatformPath = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not $RepoRoot) {
    $RepoRoot = (Resolve-Path (Join-Path $ScriptDir "..")).Path
}
else {
    $RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path
}
if (-not $ToolsDir) {
    $ToolsDir = Join-Path $RepoRoot "tools"
}

$GithubHeaders = @{ "User-Agent" = "kuibysheff-1c-live-install" }

function Write-Step([string]$Message) {
    Write-Host "==> $Message"
}

function Test-Command([string]$Name) {
    return $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

function Get-CommandPath([string]$Name) {
    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if ($null -eq $cmd) {
        return ""
    }
    return $cmd.Source
}

function Read-DotEnv([string]$Path) {
    $map = @{}
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        return $map
    }
    Get-Content -LiteralPath $Path -Encoding UTF8 | ForEach-Object {
        $line = $_.Trim()
        if ($line -eq "" -or $line.StartsWith("#")) {
            return
        }
        $eq = $line.IndexOf("=")
        if ($eq -lt 1) {
            return
        }
        $name = $line.Substring(0, $eq).Trim()
        $value = $line.Substring($eq + 1).Trim()
        if ($value.StartsWith('"') -and $value.EndsWith('"') -and $value.Length -ge 2) {
            $value = $value.Substring(1, $value.Length - 2)
        }
        elseif ($value.StartsWith("'") -and $value.EndsWith("'") -and $value.Length -ge 2) {
            $value = $value.Substring(1, $value.Length - 2)
        }
        $map[$name] = $value
    }
    return $map
}

function Save-DotEnv([string]$Path, [hashtable]$Map) {
    $order = @(
        "KBSHFF_PROVIDER_BASE_URL",
        "KBSHFF_PROVIDER_MODEL",
        "KBSHFF_PROVIDER_API_KEY_ENV",
        "OPENAI_API_KEY",
        "POLZA_API_KEY",
        "DEEPSEEK_API_KEY",
        "SNTX_SEM_CONFIG",
        "SNTX_SEM_PYTHON",
        "BSL_INDEXER",
        "CODE_INDEX_HOME",
        "BSL_LS_MCP",
        "BSL_LS_JAR",
        "JAVA_HOME",
        "KBSHFF_BIN",
        "KUIBYSHEFF_SRC"
    )
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Generated by scripts/install.ps1. Secrets stay here, not in YAML or CLI argv.")
    $written = @{}
    foreach ($name in $order) {
        if ($Map.ContainsKey($name) -and -not [string]::IsNullOrWhiteSpace([string]$Map[$name])) {
            $lines.Add("$name=$($Map[$name])")
            $written[$name] = $true
        }
    }
    foreach ($name in ($Map.Keys | Sort-Object)) {
        if ($written.ContainsKey($name)) {
            continue
        }
        if ([string]::IsNullOrWhiteSpace([string]$Map[$name])) {
            continue
        }
        $lines.Add("$name=$($Map[$name])")
    }
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, ($lines -join "`n") + "`n", $utf8)
}

function Read-Default([string]$Prompt, [string]$Default) {
    if ($NonInteractive) {
        return $Default
    }
    $suffix = if ([string]::IsNullOrWhiteSpace($Default)) { "" } else { " [$Default]" }
    $value = Read-Host "$Prompt$suffix"
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $Default
    }
    return $value
}

function Read-Secret([string]$Prompt) {
    if ($NonInteractive) {
        return ""
    }
    $sec = Read-Host $Prompt -AsSecureString
    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
    }
    finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    }
}

function Get-EnvOrMap([hashtable]$Map, [string]$Name) {
    $fromProcess = [Environment]::GetEnvironmentVariable($Name, "Process")
    if (-not [string]::IsNullOrWhiteSpace($fromProcess)) {
        return $fromProcess
    }
    if ($Map.ContainsKey($Name) -and -not [string]::IsNullOrWhiteSpace([string]$Map[$Name])) {
        return [string]$Map[$Name]
    }
    return ""
}

function Require-HostTool([string]$Name, [string]$Hint) {
    if (Test-Command $Name) {
        Write-Host "OK  $Name"
        return
    }
    throw "$Name not found in PATH. $Hint"
}

function Find-Python {
    foreach ($name in @("py", "python", "python3")) {
        if (Test-Command $name) {
            if ($name -eq "py") {
                return @("py", "-3")
            }
            return @($name)
        }
    }
    return @()
}

function Invoke-Python([string[]]$PythonCmd, [string[]]$Args, [string]$WorkDir = "") {
    $all = @()
    if ($PythonCmd.Count -gt 1) {
        $all += $PythonCmd[1..($PythonCmd.Count - 1)]
    }
    $all += $Args
    $exe = $PythonCmd[0]
    if ($WorkDir) {
        Push-Location $WorkDir
        try {
            & $exe @all
            if ($LASTEXITCODE -ne 0) {
                throw "$exe $($all -join ' ') failed (exit $LASTEXITCODE)"
            }
        }
        finally {
            Pop-Location
        }
    }
    else {
        & $exe @all
        if ($LASTEXITCODE -ne 0) {
            throw "$exe $($all -join ' ') failed (exit $LASTEXITCODE)"
        }
    }
}

function Get-GithubReleaseAsset([string]$Repo, [string]$NameMatch) {
    $rel = Invoke-RestMethod -Uri "https://api.github.com/repos/$Repo/releases/latest" -Headers $GithubHeaders
    $asset = $rel.assets | Where-Object { $_.name -like $NameMatch } | Select-Object -First 1
    if ($null -eq $asset) {
        throw "No GitHub asset matching '$NameMatch' in $Repo latest release"
    }
    return $asset
}

function Expand-ZipTo([string]$ZipPath, [string]$Dest) {
    New-Item -ItemType Directory -Force -Path $Dest | Out-Null
    Expand-Archive -LiteralPath $ZipPath -DestinationPath $Dest -Force
}

function Find-FileUnder([string]$Root, [string]$FileName) {
    $hit = Get-ChildItem -LiteralPath $Root -Recurse -File -Filter $FileName -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($null -eq $hit) {
        return ""
    }
    return $hit.FullName
}

function Ensure-Kbshff([hashtable]$EnvMap) {
    Write-Step "kbshff"
    $explicit = Get-EnvOrMap $EnvMap "KBSHFF_BIN"
    if ($explicit -and (Test-Path -LiteralPath $explicit -PathType Leaf)) {
        return (Resolve-Path -LiteralPath $explicit).Path
    }
    $fromPath = Get-CommandPath "kbshff"
    if ($fromPath) {
        return $fromPath
    }
    $parent = Split-Path -Parent $RepoRoot
    $src = Get-EnvOrMap $EnvMap "KUIBYSHEFF_SRC"
    $candidates = @()
    if ($src) { $candidates += $src }
    $candidates += @(
        (Join-Path $parent "Agent-Kuibysheff"),
        (Join-Path $parent "Agent Kuibyshev")
    )
    $foundSrc = ""
    foreach ($c in $candidates) {
        if (Test-Path -LiteralPath (Join-Path $c "Cargo.toml") -PathType Leaf) {
            $foundSrc = (Resolve-Path -LiteralPath $c).Path
            break
        }
    }
    if (-not $foundSrc) {
        if (-not (Test-Command "git")) {
            throw "kbshff not found and git is missing. Install kbshff or clone https://github.com/gazalievtimur/Agent-Kuibysheff"
        }
        if (-not (Test-Command "cargo")) {
            throw "kbshff not found. Put it on PATH, set KBSHFF_BIN, or install Rust (cargo) to build from source. See https://github.com/gazalievtimur/Agent-Kuibysheff"
        }
        $foundSrc = Join-Path $parent "Agent-Kuibysheff"
        Write-Host "Cloning Agent-Kuibysheff -> $foundSrc"
        git clone --depth 1 "https://github.com/gazalievtimur/Agent-Kuibysheff.git" $foundSrc
        if ($LASTEXITCODE -ne 0) {
            throw "git clone Agent-Kuibysheff failed"
        }
    }
    $releaseExe = Join-Path $foundSrc "target\release\kbshff.exe"
    $releaseBin = Join-Path $foundSrc "target\release\kbshff"
    if (Test-Path -LiteralPath $releaseExe) { return (Resolve-Path $releaseExe).Path }
    if (Test-Path -LiteralPath $releaseBin) { return (Resolve-Path $releaseBin).Path }
    if (-not (Test-Command "cargo")) {
        throw "cargo not found (needed to build kbshff from $foundSrc)"
    }
    Write-Host "Building kbshff from $foundSrc"
    Push-Location $foundSrc
    try {
        cargo build --release -p agent_Kuibysheff --bin kbshff
        if ($LASTEXITCODE -ne 0) {
            throw "cargo build kbshff failed"
        }
    }
    finally {
        Pop-Location
    }
    if (Test-Path -LiteralPath $releaseExe) { return (Resolve-Path $releaseExe).Path }
    if (Test-Path -LiteralPath $releaseBin) { return (Resolve-Path $releaseBin).Path }
    throw "kbshff binary missing after cargo build under $foundSrc"
}

function Ensure-BslIndexer([hashtable]$EnvMap) {
    Write-Step "bsl-indexer"
    foreach ($name in @("BSL_INDEXER", "CODE_INDEX_BIN", "BSL_INDEXER_EXE")) {
        $existing = Get-EnvOrMap $EnvMap $name
        if ($existing -and (Test-Path -LiteralPath $existing -PathType Leaf)) {
            return (Resolve-Path -LiteralPath $existing).Path
        }
    }
    foreach ($rel in @("bsl-indexer.exe", "bsl-indexer", "code-index\bsl-indexer.exe", "code-index\bsl-indexer")) {
        $p = Join-Path $ToolsDir $rel
        if (Test-Path -LiteralPath $p -PathType Leaf) {
            return (Resolve-Path $p).Path
        }
    }
    $dest = Join-Path $ToolsDir "code-index"
    New-Item -ItemType Directory -Force -Path $dest | Out-Null
    $asset = Get-GithubReleaseAsset "Regsorm/code-index-mcp" "bsl-indexer-windows-x64.zip"
    $zip = Join-Path $env:TEMP "bsl-indexer-windows-x64.zip"
    Write-Host "Downloading $($asset.browser_download_url)"
    Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $zip -Headers $GithubHeaders
    Expand-ZipTo $zip $dest
    $found = Find-FileUnder $dest "bsl-indexer.exe"
    if (-not $found) {
        throw "bsl-indexer.exe not found after extracting $zip"
    }
    $stable = Join-Path $ToolsDir "bsl-indexer.exe"
    Copy-Item -LiteralPath $found -Destination $stable -Force
    return (Resolve-Path $stable).Path
}

function Ensure-BslLsJar([hashtable]$EnvMap) {
    Write-Step "bsl-language-server JAR"
    $existing = Get-EnvOrMap $EnvMap "BSL_LS_JAR"
    if ($existing -and (Test-Path -LiteralPath $existing -PathType Leaf)) {
        return (Resolve-Path -LiteralPath $existing).Path
    }
    $stable = Join-Path $ToolsDir "bsl-ls\bsl-language-server.jar"
    if (Test-Path -LiteralPath $stable -PathType Leaf) {
        return (Resolve-Path $stable).Path
    }
    $homeJar = Join-Path $env:USERPROFILE ".claude\bsl-ls\bsl-language-server.jar"
    if (Test-Path -LiteralPath $homeJar -PathType Leaf) {
        New-Item -ItemType Directory -Force -Path (Split-Path $stable) | Out-Null
        Copy-Item -LiteralPath $homeJar -Destination $stable -Force
        return (Resolve-Path $stable).Path
    }
    New-Item -ItemType Directory -Force -Path (Split-Path $stable) | Out-Null
    $asset = Get-GithubReleaseAsset "1c-syntax/bsl-language-server" "*-exec.jar"
    Write-Host "Downloading $($asset.browser_download_url)"
    Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $stable -Headers $GithubHeaders
    return (Resolve-Path $stable).Path
}

function Ensure-BslLsMcp([hashtable]$EnvMap) {
    Write-Step "bsl-ls-mcp"
    $homeJs = Join-Path $env:USERPROFILE ".claude\bsl-ls-mcp\server.js"
    $vendorJs = Join-Path $ToolsDir "bsl-ls-mcp\server.js"
    $existing = Get-EnvOrMap $EnvMap "BSL_LS_MCP"
    if (-not $existing) {
        $existing = Get-EnvOrMap $EnvMap "BSL_LS_SERVER"
    }
    if ($existing -and (Test-Path -LiteralPath $existing -PathType Leaf)) {
        $chosen = (Resolve-Path -LiteralPath $existing).Path
    }
    elseif (Test-Path -LiteralPath $homeJs -PathType Leaf) {
        $chosen = (Resolve-Path $homeJs).Path
    }
    else {
        $chosen = $vendorJs
    }
    if ($chosen -eq $vendorJs -or $chosen.StartsWith((Join-Path $ToolsDir "bsl-ls-mcp"))) {
        if (-not (Test-Command "npm")) {
            throw "npm not found (needed for tools/bsl-ls-mcp). Install Node.js: https://nodejs.org/"
        }
        Push-Location (Join-Path $ToolsDir "bsl-ls-mcp")
        try {
            npm install --omit=dev
            if ($LASTEXITCODE -ne 0) {
                throw "npm install failed in tools/bsl-ls-mcp"
            }
        }
        finally {
            Pop-Location
        }
        $chosen = (Resolve-Path $vendorJs).Path
    }
    return $chosen
}

function Ensure-SntxSem([hashtable]$EnvMap, [string[]]$PythonCmd) {
    Write-Step "1c-sntx-sem"
    $existing = Get-EnvOrMap $EnvMap "SNTX_SEM_CONFIG"
    $src = ""
    if ($existing -and (Test-Path -LiteralPath $existing -PathType Leaf)) {
        $src = Split-Path -Parent (Resolve-Path -LiteralPath $existing).Path
    }
    else {
        $parent = Split-Path -Parent $RepoRoot
        foreach ($c in @((Join-Path $parent "1c-sntx-sem"), (Join-Path $ToolsDir "1c-sntx-sem"))) {
            if (Test-Path -LiteralPath (Join-Path $c "pyproject.toml") -PathType Leaf) {
                $src = (Resolve-Path $c).Path
                break
            }
        }
    }
    if (-not $src) {
        if (-not (Test-Command "git")) {
            throw "git not found (needed to clone 1c-sntx-sem). https://github.com/gybson63/1c-sntx-sem"
        }
        $src = Join-Path $ToolsDir "1c-sntx-sem"
        Write-Host "Cloning 1c-sntx-sem -> $src"
        git clone --depth 1 "https://github.com/gybson63/1c-sntx-sem.git" $src
        if ($LASTEXITCODE -ne 0) {
            throw "git clone 1c-sntx-sem failed"
        }
    }
    $venvPy = Join-Path $src ".venv\Scripts\python.exe"
    if (-not (Test-Path -LiteralPath $venvPy -PathType Leaf)) {
        Invoke-Python $PythonCmd @("-m", "venv", ".venv") $src
    }
    Invoke-Python @($venvPy) @("-m", "pip", "install", "-U", "pip")
    Invoke-Python @($venvPy) @("-m", "pip", "install", "-e", ".") $src
    $config = Join-Path $src "config.yaml"
    if (-not (Test-Path -LiteralPath $config -PathType Leaf)) {
        $example = Join-Path $src "config.yaml.example"
        if (-not (Test-Path -LiteralPath $example -PathType Leaf)) {
            throw "missing $example"
        }
        Copy-Item -LiteralPath $example -Destination $config
        Write-Host "Created $config from example. Edit local_configs / ingest as needed."
    }
    $doIngest = -not $SkipIngest
    if ($doIngest -and -not $NonInteractive) {
        $answer = Read-Host "Run sntx_sem ingest from a 1C platform bin folder? [y/N]"
        $doIngest = $answer -match '^[Yy]'
    }
    if ($doIngest) {
        if (-not $PlatformPath) {
            $PlatformPath = Read-Default "Path to 1C platform bin (v8 8.3.x bin folder)" ""
        }
        if ([string]::IsNullOrWhiteSpace($PlatformPath)) {
            Write-Warning "Skipping ingest: no platform path. sntx_sem search will not work until you run: $venvPy -m sntx_sem ingest --platform-path PLATFORM_BIN"
        }
        else {
            Invoke-Python @($venvPy) @("-m", "sntx_sem", "ingest", "--platform-path", $PlatformPath) $src
        }
    }
    else {
        Write-Warning "Skipping ingest. Set SNTX_SEM_CONFIG and run ingest before a live eval."
    }
    return @{
        Config = (Resolve-Path $config).Path
        Python = (Resolve-Path $venvPy).Path
    }
}

function Resolve-JavaHome([hashtable]$EnvMap) {
    $existing = Get-EnvOrMap $EnvMap "JAVA_HOME"
    if ($existing -and (Test-Path -LiteralPath $existing -PathType Container)) {
        return (Resolve-Path $existing).Path
    }
    $java = Get-CommandPath "java"
    if (-not $java) {
        throw "java not found. Install JDK 17+: https://adoptium.net/"
    }
    $probe = & java -XshowSettings:properties -version 2>&1 | Select-String "java.home"
    if ($probe) {
        $home = ($probe.ToString() -split "=", 2)[1].Trim()
        if (Test-Path -LiteralPath $home -PathType Container) {
            return $home
        }
    }
    return ""
}

function Get-ConveyorAgents {
    return @(
        @{ Id = "1c-analyst"; Skills = @("workspace", "platform_help", "conf_docs", "code_index", "local_research", "web_search") },
        @{ Id = "1c-yaxunit"; Skills = @("workspace", "yaxunit_docs", "platform_help", "code_index", "bsl_lint", "local_research", "web_search") },
        @{ Id = "1c-coder"; Skills = @("workspace", "platform_help", "code_index", "bsl_lint", "local_research") },
        @{ Id = "1c-implementer"; Skills = @("workspace", "platform_help", "code_index", "local_research", "bsl_lint") }
    )
}

function Invoke-KbshffProvider([string]$Kbshff, [string]$ProjectRoot, [string]$AgentId, [string[]]$ExpectedSkills, [string]$ProvBaseUrl, [string]$ProvModel, [string]$ProvKeyEnv) {
    Write-Step "kbshff CLI: init / import skills / provider set / check ($AgentId)"
    New-Item -ItemType Directory -Force -Path $ProjectRoot | Out-Null
    & $Kbshff init $AgentId --project-root $ProjectRoot --force
    if ($LASTEXITCODE -ne 0) {
        throw "kbshff init $AgentId failed"
    }
    $staging = Join-Path $ProjectRoot ".kuibysheff\.1c-live-import\$AgentId"
    if (Test-Path -LiteralPath $staging) {
        Remove-Item -LiteralPath $staging -Recurse -Force
    }
    New-Item -ItemType Directory -Force -Path $staging | Out-Null
    $settings = Join-Path $RepoRoot "profiles\$AgentId"
    foreach ($name in @("master_prompt.md", "skills.dsl", "rules.md")) {
        $src = Join-Path $settings $name
        if (-not (Test-Path -LiteralPath $src -PathType Leaf)) {
            throw "missing $src - conveyor profile $AgentId is incomplete"
        }
        Copy-Item -LiteralPath $src -Destination (Join-Path $staging $name) -Force
    }
    & $Kbshff config --project-root $ProjectRoot --agent $AgentId import --from $staging --force
    if ($LASTEXITCODE -ne 0) {
        throw "kbshff config import $AgentId failed"
    }
    & $Kbshff config --project-root $ProjectRoot --agent $AgentId provider set --base-url $ProvBaseUrl --model $ProvModel --api-key-env $ProvKeyEnv
    if ($LASTEXITCODE -ne 0) {
        throw "kbshff config provider set $AgentId failed"
    }
    $listed = & $Kbshff config --project-root $ProjectRoot --agent $AgentId --format json skill list
    if ($LASTEXITCODE -ne 0) {
        throw "kbshff config skill list $AgentId failed"
    }
    $listedText = ($listed | Out-String)
    foreach ($skill in $ExpectedSkills) {
        if ($listedText -notmatch [regex]::Escape($skill)) {
            throw "skill '$skill' missing after import of $AgentId. skill list: $listedText"
        }
    }
    Write-Host "OK  $AgentId skills: $($ExpectedSkills -join ', ')"
    & $Kbshff check --project-root $ProjectRoot --agent $AgentId --skip-mcp --skip-sandbox
    if ($LASTEXITCODE -ne 0) {
        throw "kbshff check $AgentId failed"
    }
}

function Install-ConveyorProfiles([string]$Kbshff, [string]$ProjectRoot, [string]$ProvBaseUrl, [string]$ProvModel, [string]$ProvKeyEnv) {
    Write-Step "Conveyor profiles (all skills)"
    foreach ($agent in Get-ConveyorAgents) {
        Invoke-KbshffProvider $Kbshff $ProjectRoot $agent.Id $agent.Skills $ProvBaseUrl $ProvModel $ProvKeyEnv
    }
}

# --- main ---

Write-Step "Host tools"
Require-HostTool "oscript" "Install OneScript 2.0: https://oscript.io/"
Require-HostTool "git" "https://git-scm.com/"
Require-HostTool "node" "https://nodejs.org/"
Require-HostTool "java" "JDK 17+: https://adoptium.net/"
$pythonCmd = Find-Python
if ($pythonCmd.Count -eq 0) {
    throw "Python 3 not found (py / python / python3). Needed for 1c-sntx-sem."
}
Write-Host "OK  python ($($pythonCmd -join ' '))"

New-Item -ItemType Directory -Force -Path $ToolsDir | Out-Null
$envPath = Join-Path $RepoRoot ".env"
$envMap = Read-DotEnv $envPath

Write-Step "AI provider (CLI applies these; the key stays in .env)"
if (-not $BaseUrl) {
    $BaseUrl = Get-EnvOrMap $envMap "KBSHFF_PROVIDER_BASE_URL"
    if (-not $BaseUrl) { $BaseUrl = "https://api.openai.com/v1" }
    $BaseUrl = Read-Default "Provider base_url" $BaseUrl
}
if (-not $Model) {
    $Model = Get-EnvOrMap $envMap "KBSHFF_PROVIDER_MODEL"
    if (-not $Model) { $Model = "gpt-4o" }
    $Model = Read-Default "Model" $Model
}
if (-not $ApiKeyEnvName) {
    $ApiKeyEnvName = Get-EnvOrMap $envMap "KBSHFF_PROVIDER_API_KEY_ENV"
    if (-not $ApiKeyEnvName) { $ApiKeyEnvName = "OPENAI_API_KEY" }
    $ApiKeyEnvName = Read-Default "API key env var name" $ApiKeyEnvName
}
$apiKey = Get-EnvOrMap $envMap $ApiKeyEnvName
if (-not $apiKey) {
    $apiKey = [Environment]::GetEnvironmentVariable($ApiKeyEnvName, "Process")
}
if (-not $apiKey) {
    $apiKey = Read-Secret "Value for $ApiKeyEnvName (not echoed, not passed to CLI argv)"
}
if ([string]::IsNullOrWhiteSpace($apiKey)) {
    throw "API key for $ApiKeyEnvName is required (set env, .env, or enter it interactively)"
}
[Environment]::SetEnvironmentVariable($ApiKeyEnvName, $apiKey, "Process")

$kbshff = Ensure-Kbshff $envMap
$indexer = Ensure-BslIndexer $envMap
$jar = Ensure-BslLsJar $envMap
$mcpJs = Ensure-BslLsMcp $envMap
$sntx = Ensure-SntxSem $envMap $pythonCmd
$javaHome = Resolve-JavaHome $envMap

$envMap["KBSHFF_PROVIDER_BASE_URL"] = $BaseUrl
$envMap["KBSHFF_PROVIDER_MODEL"] = $Model
$envMap["KBSHFF_PROVIDER_API_KEY_ENV"] = $ApiKeyEnvName
$envMap[$ApiKeyEnvName] = $apiKey
$envMap["SNTX_SEM_CONFIG"] = $sntx.Config
$envMap["SNTX_SEM_PYTHON"] = $sntx.Python
$envMap["BSL_INDEXER"] = $indexer
$envMap["CODE_INDEX_HOME"] = Split-Path -Parent $indexer
$envMap["BSL_LS_MCP"] = $mcpJs
$envMap["BSL_LS_JAR"] = $jar
$envMap["KBSHFF_BIN"] = $kbshff
if ($javaHome) {
    $envMap["JAVA_HOME"] = $javaHome
    [Environment]::SetEnvironmentVariable("JAVA_HOME", $javaHome, "Process")
}
foreach ($name in @("KBSHFF_PROVIDER_BASE_URL", "KBSHFF_PROVIDER_MODEL", "KBSHFF_PROVIDER_API_KEY_ENV", "SNTX_SEM_CONFIG", "SNTX_SEM_PYTHON", "BSL_INDEXER", "BSL_LS_MCP", "BSL_LS_JAR", "KBSHFF_BIN")) {
    [Environment]::SetEnvironmentVariable($name, $envMap[$name], "Process")
}

Save-DotEnv $envPath $envMap
Write-Host "Wrote $envPath"

Install-ConveyorProfiles $kbshff $RepoRoot $BaseUrl $Model $ApiKeyEnvName

Write-Step "harness dry-run"
$oscript = Get-CommandPath "oscript"
& $oscript -encoding=utf-8 (Join-Path $RepoRoot "harness\run.os") --repo-root $RepoRoot --dry-run
if ($LASTEXITCODE -ne 0) {
    throw "dry-run failed"
}

Write-Host ""
Write-Host "Install OK. Conveyor is ready."
Write-Host "Profiles with skills: 1c-analyst, 1c-yaxunit, 1c-coder, 1c-implementer"
Write-Host "Live eval:  .\harness\run.ps1"
Write-Host "Howto:      docs\howto-pipeline.md"
Write-Host "CLI help:   kbshff help config"
exit 0
