#Requires -Version 5.1
<#
.SYNOPSIS
  Bootstrap kuibysheff-1c-live: host checks, MCP tools, .env secrets, kbshff CLI provider.
#>
param(
    [string]$RepoRoot = "",
    [string]$ToolsDir = "",
    [switch]$SkipIngest,
    [switch]$NonInteractive,
    [string]$BaseUrl = "",
    [string]$Model = "",
    [string]$ModelAnalyst = "",
    [string]$ModelYaxunit = "",
    [string]$ModelCoder = "",
    [string]$ModelImplementer = "",
    [string]$ApiKeyEnvName = "",
    [string]$PlatformPath = "",
    [string]$OscriptVersion = "stable"
)

# Per-agent models (shared base_url / api_key). Populated by Read-ProviderSettings.
$script:AgentModels = @{}

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not $RepoRoot) {
    $RepoRoot = (Resolve-Path (Join-Path $ScriptDir "..")).Path
}
else {
    $RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path
}
if (-not $ToolsDir) {
    $ToolsDir = Join-Path $RepoRoot "tools"
}

$GithubHeaders = @{ "User-Agent" = "kuibysheff-1c-live-install" }

function Write-Step([string]$Message) {
    Write-Host "==> $Message"
}

function Write-Hint([string]$Message) {
    if ($NonInteractive) {
        return
    }
    if ([string]::IsNullOrEmpty($Message)) {
        Write-Host ""
        return
    }
    Write-Host $Message -ForegroundColor DarkGray
}

function Write-InputLabel([string]$Prompt) {
    Write-Host "[ВВОД] " -NoNewline -ForegroundColor Black -BackgroundColor Cyan
    Write-Host $Prompt -NoNewline -ForegroundColor Cyan
    Write-Host ": " -NoNewline -ForegroundColor Cyan
}

function Read-Prompt([string]$Prompt) {
    if ($NonInteractive) {
        return ""
    }
    Write-InputLabel $Prompt
    return Read-Host
}

function Test-Command([string]$Name) {
    return $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

function Get-CommandPath([string]$Name) {
    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if ($null -eq $cmd) {
        return ""
    }
    return $cmd.Source
}

function Read-DotEnv([string]$Path) {
    $map = @{}
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        return $map
    }
    Get-Content -LiteralPath $Path -Encoding UTF8 | ForEach-Object {
        $line = $_.Trim()
        if ($line -eq "" -or $line.StartsWith("#")) {
            return
        }
        $eq = $line.IndexOf("=")
        if ($eq -lt 1) {
            return
        }
        $name = $line.Substring(0, $eq).Trim()
        $value = $line.Substring($eq + 1).Trim()
        if ($value.StartsWith('"') -and $value.EndsWith('"') -and $value.Length -ge 2) {
            $value = $value.Substring(1, $value.Length - 2)
        }
        elseif ($value.StartsWith("'") -and $value.EndsWith("'") -and $value.Length -ge 2) {
            $value = $value.Substring(1, $value.Length - 2)
        }
        $map[$name] = $value
    }
    return $map
}

function Format-DotEnvValue([string]$Value) {
    # dotenvy treats unquoted `\` as an escape (`C:\Git` fails at the first slash).
    # Single quotes are literal in dotenvy and OneScript only strips matching quotes.
    if ($Value -notmatch '[#''"\\\s]') {
        return $Value
    }
    if ($Value.Contains("'")) {
        throw "Cannot encode dotenv value with a single quote for both dotenvy and OneScript"
    }
    return "'$Value'"
}

function Get-AgentModelEnvName([string]$AgentId) {
    return "KBSHFF_PROVIDER_MODEL_" + ($AgentId.ToUpperInvariant() -replace '-', '_')
}

function Save-DotEnv([string]$Path, [hashtable]$Map) {
    $order = @(
        "KBSHFF_PROVIDER_BASE_URL",
        "KBSHFF_PROVIDER_MODEL",
        "KBSHFF_PROVIDER_MODEL_1C_ANALYST",
        "KBSHFF_PROVIDER_MODEL_1C_YAXUNIT",
        "KBSHFF_PROVIDER_MODEL_1C_CODER",
        "KBSHFF_PROVIDER_MODEL_1C_IMPLEMENTER",
        "KBSHFF_PROVIDER_API_KEY_ENV",
        "OPENAI_API_KEY",
        "POLZA_API_KEY",
        "DEEPSEEK_API_KEY",
        "SNTX_SEM_CONFIG",
        "SNTX_SEM_PYTHON",
        "BSL_INDEXER",
        "CODE_INDEX_HOME",
        "BSL_LS_MCP",
        "BSL_LS_JAR",
        "JAVA_HOME",
        "KBSHFF_BIN",
        "OSCRIPT_BIN",
        "KUIBYSHEFF_SRC"
    )
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Generated by scripts/install.ps1. Secrets stay here, not in YAML or CLI argv.")
    $written = @{}
    foreach ($name in $order) {
        if ($Map.ContainsKey($name) -and -not [string]::IsNullOrWhiteSpace([string]$Map[$name])) {
            $lines.Add("$name=$(Format-DotEnvValue ([string]$Map[$name]))")
            $written[$name] = $true
        }
    }
    foreach ($name in ($Map.Keys | Sort-Object)) {
        if ($written.ContainsKey($name)) {
            continue
        }
        if ([string]::IsNullOrWhiteSpace([string]$Map[$name])) {
            continue
        }
        $lines.Add("$name=$(Format-DotEnvValue ([string]$Map[$name]))")
    }
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, ($lines -join "`n") + "`n", $utf8)
}

function Read-Default([string]$Prompt, [string]$Default) {
    if ($NonInteractive) {
        return $Default
    }
    $suffix = if ([string]::IsNullOrWhiteSpace($Default)) { "" } else { " [$Default]" }
    Write-InputLabel "$Prompt$suffix"
    $value = Read-Host
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $Default
    }
    return $value
}

function Test-ValidEnvVarName([string]$Name) {
    return $Name -match '^[A-Za-z_][A-Za-z0-9_]*$'
}

function Test-LooksLikeApiKey([string]$Value) {
    if ([string]::IsNullOrWhiteSpace($Value)) {
        return $false
    }
    if ($Value -match '(?i)^sk[-_]') {
        return $true
    }
    # Long token that is not a legal env var name (hyphens, etc.)
    if ($Value.Length -ge 20 -and -not (Test-ValidEnvVarName $Value)) {
        return $true
    }
    return $false
}

function Read-Secret([string]$Prompt) {
    if ($NonInteractive) {
        return ""
    }
    Write-InputLabel $Prompt
    $sec = Read-Host -AsSecureString
    if ($null -eq $sec -or $sec.Length -eq 0) {
        return ""
    }
    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
    }
    finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    }
}

function Get-EnvOrMap([hashtable]$Map, [string]$Name) {
    $fromProcess = [Environment]::GetEnvironmentVariable($Name, "Process")
    if (-not [string]::IsNullOrWhiteSpace($fromProcess)) {
        return $fromProcess
    }
    if ($Map.ContainsKey($Name) -and -not [string]::IsNullOrWhiteSpace([string]$Map[$Name])) {
        return [string]$Map[$Name]
    }
    return ""
}

function Require-HostTool([string]$Name, [string]$Hint) {
    if (Test-Command $Name) {
        Write-Host "OK  $Name"
        return
    }
    throw "$Name not found in PATH. $Hint"
}

function Confirm-OptionalHostGaps([string[]]$Gaps) {
    if ($null -eq $Gaps -or $Gaps.Count -eq 0) {
        return
    }
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Yellow
    Write-Host "ВНИМАНИЕ: рекомендуемые инструменты не найдены" -ForegroundColor Yellow
    Write-Host "============================================================" -ForegroundColor Yellow
    foreach ($gap in $Gaps) {
        Write-Host "  * $gap" -ForegroundColor Yellow
    }
    Write-Host ""
    Write-Host "Рекомендуем установить их СЕЙЧАС (до продолжения install):" -ForegroundColor Yellow
    Write-Host "  docs/prerequisites.md" -ForegroundColor Yellow
    Write-Host "Без Node.js / Java 17+ штатный MCP bsl-language-server не настроится." -ForegroundColor Yellow
    Write-Host "Без bin платформы 1С ingest справки sntx_sem будет недоступен (семантический поиск)." -ForegroundColor Yellow
    Write-Host "Свой MCP без Node/Java можно подключить позже через CLI / .env." -ForegroundColor Yellow
    Write-Host ""
    if ($NonInteractive) {
        Write-Warning "NonInteractive: продолжаем без рекомендуемых инструментов."
        return
    }
    $ans = Read-Prompt "Подтверждение: продолжить без рекомендуемых инструментов? [y/N]"
    if ($ans -notmatch '^(?i)(y|yes|д|да)$') {
        throw "Install cancelled. Install missing tools (see docs/prerequisites.md) and re-run."
    }
    Write-Host "Continuing without recommended tools..."
}

function Find-Python {
    foreach ($name in @("py", "python", "python3")) {
        if (Test-Command $name) {
            if ($name -eq "py") {
                return @("py", "-3")
            }
            return @($name)
        }
    }
    return @()
}

function Invoke-NativeProcess {
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [string[]]$ArgumentList = @(),
        [string]$WorkDir = "",
        [string]$FailMessage = "",
        [switch]$CaptureOutput
    )
    # PS 5.1: native stderr becomes a terminating error when ErrorActionPreference=Stop.
    # Splatting arrays that start with "-m" also looks like a named parameter.
    $oldEap = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    $code = 0
    $output = $null
    try {
        if ($WorkDir) {
            Push-Location -LiteralPath $WorkDir
        }
        try {
            if ($CaptureOutput) {
                $output = & $FilePath @ArgumentList
            }
            else {
                # Write-Host so native stdout does not pollute function return values.
                & $FilePath @ArgumentList | ForEach-Object { Write-Host $_ }
            }
            $code = $LASTEXITCODE
        }
        finally {
            if ($WorkDir) {
                Pop-Location
            }
        }
    }
    finally {
        $ErrorActionPreference = $oldEap
    }
    if ($code -ne 0) {
        if ([string]::IsNullOrWhiteSpace($FailMessage)) {
            $FailMessage = "$FilePath $($ArgumentList -join ' ') failed (exit $code)"
        }
        throw $FailMessage
    }
    if ($CaptureOutput) {
        return $output
    }
}

function Invoke-Python {
    param(
        [Parameter(Mandatory = $true)][string[]]$PythonCmd,
        [Parameter(Mandatory = $true)][string[]]$PythonArgs,
        [string]$WorkDir = ""
    )
    if ($null -eq $PythonCmd -or $PythonCmd.Count -eq 0) {
        throw "PythonCmd is empty"
    }
    $exe = $PythonCmd[0]
    $all = @()
    if ($PythonCmd.Count -gt 1) {
        $all += $PythonCmd[1..($PythonCmd.Count - 1)]
    }
    $all += $PythonArgs
    Invoke-NativeProcess -FilePath $exe -ArgumentList $all -WorkDir $WorkDir
}

function Find-OscriptPath {
    $fromPath = Get-CommandPath "oscript"
    if ($fromPath) {
        return $fromPath
    }
    $candidates = New-Object System.Collections.Generic.List[string]
    if (-not [string]::IsNullOrWhiteSpace($env:OVM_INSTALL_PATH)) {
        $candidates.Add((Join-Path $env:OVM_INSTALL_PATH "current\bin\oscript.exe"))
        $candidates.Add((Join-Path $env:OVM_INSTALL_PATH "current\bin\oscript"))
    }
    if (-not [string]::IsNullOrWhiteSpace($env:LOCALAPPDATA)) {
        $candidates.Add((Join-Path $env:LOCALAPPDATA "ovm\current\bin\oscript.exe"))
    }
    if (-not [string]::IsNullOrWhiteSpace($env:USERPROFILE)) {
        $candidates.Add((Join-Path $env:USERPROFILE "ovm\current\bin\oscript.exe"))
    }
    foreach ($c in $candidates) {
        if ($c -and (Test-Path -LiteralPath $c -PathType Leaf)) {
            return (Resolve-Path -LiteralPath $c).Path
        }
    }
    return ""
}

function Ensure-Oscript {
    Write-Step "OneScript (ovm)"
    $existing = Find-OscriptPath
    if ($existing) {
        $binDir = Split-Path -Parent $existing
        if ($env:Path -notlike ("*{0}*" -f $binDir)) {
            $env:Path = "$binDir;$env:Path"
        }
        Write-Host "OK  oscript ($existing)"
        return $existing
    }

    Write-Host "oscript не найден в PATH."
    Write-Host "Установим OneScript через OVM: https://github.com/oscript-library/ovm"
    Write-Host "Версия: $OscriptVersion (нужен .NET Framework 4.8+ для ovm.exe на Windows)."
    if (-not $NonInteractive) {
        $ans = Read-Prompt "Подтверждение: установить OneScript ($OscriptVersion) через ovm? [Y/n]"
        if ($ans -match '^(?i)(n|no|н|нет)$') {
            throw "oscript required. Install via OVM (docs/prerequisites.md) or re-run and accept install."
        }
    }
    else {
        Write-Host "NonInteractive: installing OneScript via ovm ($OscriptVersion)..."
    }

    $ovmDir = Join-Path $ToolsDir "ovm"
    New-Item -ItemType Directory -Force -Path $ovmDir | Out-Null
    $ovmExe = Join-Path $ovmDir "ovm.exe"
    if (-not (Test-Path -LiteralPath $ovmExe -PathType Leaf)) {
        $asset = Get-GithubReleaseAsset "oscript-library/ovm" "ovm.exe"
        Save-RemoteFile -Uri $asset.browser_download_url -OutFile $ovmExe -Activity "ovm"
    }

    Invoke-NativeProcess -FilePath $ovmExe -ArgumentList @("install", $OscriptVersion) -FailMessage "ovm install $OscriptVersion failed"
    Invoke-NativeProcess -FilePath $ovmExe -ArgumentList @("use", $OscriptVersion) -FailMessage "ovm use $OscriptVersion failed"

    $existing = Find-OscriptPath
    if (-not $existing) {
        throw "oscript still not found after ovm install/use. Check OVM_INSTALL_PATH or open a new shell. docs/prerequisites.md"
    }
    $binDir = Split-Path -Parent $existing
    $env:Path = "$binDir;$env:Path"
    Write-Host "OK  oscript ($existing) via ovm"
    Write-Host "Hint: add to user PATH for new shells: $binDir"
    return $existing
}

function Get-GithubReleaseAsset([string]$Repo, [string]$NameMatch) {
    $rel = Invoke-RestMethod -Uri "https://api.github.com/repos/$Repo/releases/latest" -Headers $GithubHeaders
    $asset = $rel.assets | Where-Object { $_.name -like $NameMatch } | Select-Object -First 1
    if ($null -eq $asset) {
        throw "No GitHub asset matching '$NameMatch' in $Repo latest release"
    }
    return $asset
}

function Save-RemoteFile {
    param(
        [Parameter(Mandatory = $true)][string]$Uri,
        [Parameter(Mandatory = $true)][string]$OutFile,
        [string]$Activity = "Downloading"
    )
    Write-Host "Downloading $Uri"
    $curl = Get-CommandPath "curl.exe"
    if ($curl) {
        $oldEap = $ErrorActionPreference
        $ErrorActionPreference = "Continue"
        try {
            & $curl -fL --progress-bar -A "kuibysheff-1c-live-install" -o $OutFile $Uri
            if ($LASTEXITCODE -ne 0) {
                throw "curl download failed (exit $LASTEXITCODE): $Uri"
            }
        }
        finally {
            $ErrorActionPreference = $oldEap
        }
        return
    }
    Write-Host "(curl.exe not found; download without progress bar: $Activity)"
    $oldEap = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        Invoke-WebRequest -Uri $Uri -OutFile $OutFile -Headers $GithubHeaders -UseBasicParsing
    }
    finally {
        $ErrorActionPreference = $oldEap
    }
}

function Expand-ZipTo([string]$ZipPath, [string]$Dest) {
    New-Item -ItemType Directory -Force -Path $Dest | Out-Null
    Expand-Archive -LiteralPath $ZipPath -DestinationPath $Dest -Force
}

function Find-FileUnder([string]$Root, [string]$FileName) {
    $hit = Get-ChildItem -LiteralPath $Root -Recurse -File -Filter $FileName -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($null -eq $hit) {
        return ""
    }
    return $hit.FullName
}

function Install-KbshffFromRelease {
    $stable = Join-Path $ToolsDir "kbshff.exe"
    $asset = Get-GithubReleaseAsset "gazalievtimur/Agent-Kuibysheff" "agent_Kuibysheff-*-x86_64-pc-windows-msvc.zip"
    $zip = Join-Path $env:TEMP "kbshff-windows-msvc.zip"
    $extract = Join-Path $env:TEMP "kbshff-windows-msvc-extract"
    if (Test-Path -LiteralPath $extract) {
        Remove-Item -LiteralPath $extract -Recurse -Force
    }
    Save-RemoteFile -Uri $asset.browser_download_url -OutFile $zip -Activity "kbshff release"
    $shaAsset = $null
    try {
        $shaAsset = Get-GithubReleaseAsset "gazalievtimur/Agent-Kuibysheff" "agent_Kuibysheff-*-x86_64-pc-windows-msvc.zip.sha256"
    }
    catch {
        Write-Warning "No .sha256 asset for kbshff release; skipping checksum"
    }
    if ($shaAsset) {
        $shaFile = Join-Path $env:TEMP "kbshff-windows-msvc.zip.sha256"
        Save-RemoteFile -Uri $shaAsset.browser_download_url -OutFile $shaFile -Activity "kbshff checksum"
        $expected = ((Get-Content -LiteralPath $shaFile -Raw) -split '\s+')[0].Trim().ToLowerInvariant()
        $actual = (Get-FileHash -LiteralPath $zip -Algorithm SHA256).Hash.ToLowerInvariant()
        if ($expected -and $expected -ne $actual) {
            throw "kbshff zip SHA256 mismatch (expected $expected, got $actual)"
        }
        Write-Host "OK  kbshff SHA256"
    }
    Expand-ZipTo $zip $extract
    $found = Find-FileUnder $extract "kbshff.exe"
    if (-not $found) {
        throw "kbshff.exe not found in release archive"
    }
    New-Item -ItemType Directory -Force -Path $ToolsDir | Out-Null
    Copy-Item -LiteralPath $found -Destination $stable -Force
    Write-Host "Installed kbshff -> $stable"
    return (Resolve-Path $stable).Path
}

function Ensure-Kbshff([hashtable]$EnvMap) {
    Write-Step "kbshff"
    $explicit = Get-EnvOrMap $EnvMap "KBSHFF_BIN"
    if ($explicit -and (Test-Path -LiteralPath $explicit -PathType Leaf)) {
        return (Resolve-Path -LiteralPath $explicit).Path
    }
    $vendored = Join-Path $ToolsDir "kbshff.exe"
    if (Test-Path -LiteralPath $vendored -PathType Leaf) {
        return (Resolve-Path $vendored).Path
    }
    $fromPath = Get-CommandPath "kbshff"
    if ($fromPath) {
        return $fromPath
    }
    $parent = Split-Path -Parent $RepoRoot
    $src = Get-EnvOrMap $EnvMap "KUIBYSHEFF_SRC"
    $candidates = @()
    if ($src) { $candidates += $src }
    $candidates += @(
        (Join-Path $parent "Agent-Kuibysheff"),
        (Join-Path $parent "Agent Kuibyshev")
    )
    $foundSrc = ""
    foreach ($c in $candidates) {
        if (Test-Path -LiteralPath (Join-Path $c "Cargo.toml") -PathType Leaf) {
            $foundSrc = (Resolve-Path -LiteralPath $c).Path
            $releaseExe = Join-Path $foundSrc "target\release\kbshff.exe"
            $releaseBin = Join-Path $foundSrc "target\release\kbshff"
            if (Test-Path -LiteralPath $releaseExe) { return (Resolve-Path $releaseExe).Path }
            if (Test-Path -LiteralPath $releaseBin) { return (Resolve-Path $releaseBin).Path }
            break
        }
    }
    try {
        return Install-KbshffFromRelease
    }
    catch {
        Write-Warning "GitHub release download failed: $($_.Exception.Message)"
    }
    if (-not $foundSrc) {
        if (-not (Test-Command "git")) {
            throw "kbshff not found and git is missing. Install kbshff or clone https://github.com/gazalievtimur/Agent-Kuibysheff"
        }
        if (-not (Test-Command "cargo")) {
            throw "kbshff not found. Put it on PATH, set KBSHFF_BIN, or install Rust (cargo) to build from source. See https://github.com/gazalievtimur/Agent-Kuibysheff"
        }
        $foundSrc = Join-Path $parent "Agent-Kuibysheff"
        Write-Host "Cloning Agent-Kuibysheff -> $foundSrc"
        Invoke-NativeProcess -FilePath "git" -ArgumentList @("clone", "--depth", "1", "https://github.com/gazalievtimur/Agent-Kuibysheff.git", $foundSrc) -FailMessage "git clone Agent-Kuibysheff failed"
    }
    $releaseExe = Join-Path $foundSrc "target\release\kbshff.exe"
    $releaseBin = Join-Path $foundSrc "target\release\kbshff"
    if (Test-Path -LiteralPath $releaseExe) { return (Resolve-Path $releaseExe).Path }
    if (Test-Path -LiteralPath $releaseBin) { return (Resolve-Path $releaseBin).Path }
    if (-not (Test-Command "cargo")) {
        throw "cargo not found (needed to build kbshff from $foundSrc)"
    }
    Write-Host "Building kbshff from $foundSrc"
    Invoke-NativeProcess -FilePath "cargo" -ArgumentList @("build", "--release", "-p", "agent_Kuibysheff", "--bin", "kbshff") -WorkDir $foundSrc -FailMessage "cargo build kbshff failed"
    if (Test-Path -LiteralPath $releaseExe) { return (Resolve-Path $releaseExe).Path }
    if (Test-Path -LiteralPath $releaseBin) { return (Resolve-Path $releaseBin).Path }
    throw "kbshff binary missing after cargo build under $foundSrc"
}

function Ensure-BslIndexer([hashtable]$EnvMap) {
    Write-Step "bsl-indexer"
    foreach ($name in @("BSL_INDEXER", "CODE_INDEX_BIN", "BSL_INDEXER_EXE")) {
        $existing = Get-EnvOrMap $EnvMap $name
        if ($existing -and (Test-Path -LiteralPath $existing -PathType Leaf)) {
            return (Resolve-Path -LiteralPath $existing).Path
        }
    }
    foreach ($rel in @("bsl-indexer.exe", "bsl-indexer", "code-index\bsl-indexer.exe", "code-index\bsl-indexer")) {
        $p = Join-Path $ToolsDir $rel
        if (Test-Path -LiteralPath $p -PathType Leaf) {
            return (Resolve-Path $p).Path
        }
    }
    $dest = Join-Path $ToolsDir "code-index"
    New-Item -ItemType Directory -Force -Path $dest | Out-Null
    $asset = Get-GithubReleaseAsset "Regsorm/code-index-mcp" "bsl-indexer-windows-x64.zip"
    $zip = Join-Path $env:TEMP "bsl-indexer-windows-x64.zip"
    Save-RemoteFile -Uri $asset.browser_download_url -OutFile $zip -Activity "bsl-indexer"
    Expand-ZipTo $zip $dest
    $found = Find-FileUnder $dest "bsl-indexer.exe"
    if (-not $found) {
        throw "bsl-indexer.exe not found after extracting $zip"
    }
    $stable = Join-Path $ToolsDir "bsl-indexer.exe"
    Copy-Item -LiteralPath $found -Destination $stable -Force
    return (Resolve-Path $stable).Path
}

function Ensure-BslLsJar([hashtable]$EnvMap) {
    Write-Step "bsl-language-server JAR (optional)"
    $existing = Get-EnvOrMap $EnvMap "BSL_LS_JAR"
    if ($existing -and (Test-Path -LiteralPath $existing -PathType Leaf)) {
        return (Resolve-Path -LiteralPath $existing).Path
    }
    $stable = Join-Path $ToolsDir "bsl-ls\bsl-language-server.jar"
    if (Test-Path -LiteralPath $stable -PathType Leaf) {
        return (Resolve-Path $stable).Path
    }
    $homeJar = Join-Path $env:USERPROFILE ".claude\bsl-ls\bsl-language-server.jar"
    if (Test-Path -LiteralPath $homeJar -PathType Leaf) {
        New-Item -ItemType Directory -Force -Path (Split-Path $stable) | Out-Null
        Copy-Item -LiteralPath $homeJar -Destination $stable -Force
        return (Resolve-Path $stable).Path
    }
    if (-not (Test-Command "curl") -and -not (Test-Command "curl.exe")) {
        Write-Warning "Skipping BSL LS JAR download (no curl). Default bsl-language-server MCP needs JAR+Java; see docs/prerequisites.md"
        return ""
    }
    New-Item -ItemType Directory -Force -Path (Split-Path $stable) | Out-Null
    try {
        $asset = Get-GithubReleaseAsset "1c-syntax/bsl-language-server" "*-exec.jar"
        Save-RemoteFile -Uri $asset.browser_download_url -OutFile $stable -Activity "bsl-language-server JAR"
        return (Resolve-Path $stable).Path
    }
    catch {
        Write-Warning "Skipping BSL LS JAR: $_"
        return ""
    }
}

function Ensure-BslLsMcp([hashtable]$EnvMap) {
    Write-Step "bsl-ls-mcp (optional; needs Node.js)"
    $homeJs = Join-Path $env:USERPROFILE ".claude\bsl-ls-mcp\server.js"
    $vendorJs = Join-Path $ToolsDir "bsl-ls-mcp\server.js"
    $existing = Get-EnvOrMap $EnvMap "BSL_LS_MCP"
    if (-not $existing) {
        $existing = Get-EnvOrMap $EnvMap "BSL_LS_SERVER"
    }
    if ($existing -and (Test-Path -LiteralPath $existing -PathType Leaf)) {
        return (Resolve-Path -LiteralPath $existing).Path
    }
    if (Test-Path -LiteralPath $homeJs -PathType Leaf) {
        return (Resolve-Path $homeJs).Path
    }
    if (-not (Test-Command "npm")) {
        Write-Warning "Skipping tools/bsl-ls-mcp (Node.js/npm not found). Install Node for default BSL MCP, or point BSL_LS_MCP at your own server. docs/prerequisites.md"
        return ""
    }
    if (-not (Test-Path -LiteralPath $vendorJs -PathType Leaf)) {
        Write-Warning "Skipping bsl-ls-mcp: missing $vendorJs"
        return ""
    }
    try {
        Invoke-NativeProcess -FilePath "npm" -ArgumentList @("install", "--omit=dev") -WorkDir (Join-Path $ToolsDir "bsl-ls-mcp") -FailMessage "npm install failed in tools/bsl-ls-mcp"
        return (Resolve-Path $vendorJs).Path
    }
    catch {
        Write-Warning "Skipping bsl-ls-mcp: $_"
        return ""
    }
}

function Find-1cPlatformBins {
    $bins = New-Object System.Collections.Generic.List[string]
    $roots = New-Object System.Collections.Generic.List[string]
    if (-not [string]::IsNullOrWhiteSpace($env:ProgramFiles)) {
        $roots.Add((Join-Path $env:ProgramFiles "1cv8"))
    }
    $pf86 = ${env:ProgramFiles(x86)}
    if (-not [string]::IsNullOrWhiteSpace($pf86)) {
        $roots.Add((Join-Path $pf86 "1cv8"))
    }
    foreach ($root in $roots) {
        if (-not (Test-Path -LiteralPath $root -PathType Container)) {
            continue
        }
        Get-ChildItem -LiteralPath $root -Directory -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -like "8.3.*" } |
            ForEach-Object {
                $bin = Join-Path $_.FullName "bin"
                if (-not (Test-Path -LiteralPath $bin -PathType Container)) {
                    return
                }
                $has = (Test-Path -LiteralPath (Join-Path $bin "1cv8.exe")) -or (Test-Path -LiteralPath (Join-Path $bin "ibcmd.exe"))
                if ($has) {
                    $bins.Add((Resolve-Path -LiteralPath $bin).Path)
                }
            }
    }
    return @($bins | Sort-Object -Descending)
}

function Select-PlatformBinForIngest {
    if ($PlatformPath) {
        return $PlatformPath
    }
    if ($NonInteractive) {
        return ""
    }
    Write-Hint ""
    Write-Hint "Ingest строит индекс справки платформы для MCP sntx_sem (поиск синтаксиса/справки на live-прогоне)."
    Write-Hint "Нужен каталог bin вашей лицензионной платформы 1С (обычно ...\1cv8\8.3.xx\bin)."
    Write-Hint "HBK в репозиторий не копируется."
    $found = @(Find-1cPlatformBins)
    if ($found.Count -eq 0) {
        Write-Hint "Установленные 8.3.*\bin не найдены автоматически."
        $answer = Read-Default "Путь к bin платформы 1С (пусто = пропуск)" ""
        return $answer
    }
    Write-Host "Найдены каталоги bin платформы:"
    for ($i = 0; $i -lt $found.Count; $i++) {
        Write-Host ("  [{0}] {1}" -f ($i + 1), $found[$i])
    }
    $manualIdx = $found.Count + 1
    $skipIdx = $found.Count + 2
    Write-Host ("  [{0}] ввести путь вручную" -f $manualIdx)
    Write-Host ("  [{0}] пропустить ingest" -f $skipIdx)
    $choice = Read-Default "Номер выбора" "1"
    $n = 0
    if (-not [int]::TryParse($choice, [ref]$n)) {
        Write-Warning "Неверный выбор - ingest пропущен"
        return ""
    }
    if ($n -ge 1 -and $n -le $found.Count) {
        return $found[$n - 1]
    }
    if ($n -eq $manualIdx) {
        return Read-Default "Путь к bin платформы 1С (пусто = пропуск)" ""
    }
    return ""
}

function Ensure-SntxSem([hashtable]$EnvMap, [string[]]$PythonCmd) {
    Write-Step "1c-sntx-sem"
    $existing = Get-EnvOrMap $EnvMap "SNTX_SEM_CONFIG"
    $src = ""
    if ($existing -and (Test-Path -LiteralPath $existing -PathType Leaf)) {
        $src = Split-Path -Parent (Resolve-Path -LiteralPath $existing).Path
    }
    else {
        $parent = Split-Path -Parent $RepoRoot
        foreach ($c in @((Join-Path $parent "1c-sntx-sem"), (Join-Path $ToolsDir "1c-sntx-sem"))) {
            if (Test-Path -LiteralPath (Join-Path $c "pyproject.toml") -PathType Leaf) {
                $src = (Resolve-Path $c).Path
                break
            }
        }
    }
    if (-not $src) {
        if (-not (Test-Command "git")) {
            throw "git not found (needed to clone 1c-sntx-sem). https://github.com/gybson63/1c-sntx-sem"
        }
        $src = Join-Path $ToolsDir "1c-sntx-sem"
        Write-Host "Cloning 1c-sntx-sem -> $src"
        Invoke-NativeProcess -FilePath "git" -ArgumentList @("clone", "--depth", "1", "https://github.com/gybson63/1c-sntx-sem.git", $src) -FailMessage "git clone 1c-sntx-sem failed"
    }
    $venvPy = Join-Path $src ".venv\Scripts\python.exe"
    if (-not (Test-Path -LiteralPath $venvPy -PathType Leaf)) {
        Invoke-Python -PythonCmd $PythonCmd -PythonArgs @("-m", "venv", ".venv") -WorkDir $src
    }
    Invoke-Python -PythonCmd @($venvPy) -PythonArgs @("-m", "pip", "install", "-U", "pip")
    Invoke-Python -PythonCmd @($venvPy) -PythonArgs @("-m", "pip", "install", "-e", ".") -WorkDir $src
    $config = Join-Path $src "config.yaml"
    if (-not (Test-Path -LiteralPath $config -PathType Leaf)) {
        $example = Join-Path $src "config.yaml.example"
        if (-not (Test-Path -LiteralPath $example -PathType Leaf)) {
            throw "missing $example"
        }
        Copy-Item -LiteralPath $example -Destination $config
        Write-Host "Created $config from example. Edit local_configs / ingest as needed."
    }
    $doIngest = -not $SkipIngest
    $chosenPlatform = $PlatformPath
    if ($doIngest) {
        if (-not $chosenPlatform) {
            $chosenPlatform = Select-PlatformBinForIngest
        }
        if ([string]::IsNullOrWhiteSpace($chosenPlatform)) {
            Write-Warning "Skipping ingest: no platform path. sntx_sem search will not work until you run: $venvPy -m sntx_sem ingest --platform-path PLATFORM_BIN"
        }
        else {
            Invoke-Python -PythonCmd @($venvPy) -PythonArgs @("-m", "sntx_sem", "ingest", "--platform-path", $chosenPlatform) -WorkDir $src
        }
    }
    else {
        Write-Warning "Skipping ingest. Set SNTX_SEM_CONFIG and run ingest before a live eval."
    }
    return @{
        Config = (Resolve-Path $config).Path
        Python = (Resolve-Path $venvPy).Path
    }
}

function Resolve-JavaHome([hashtable]$EnvMap) {
    $existing = Get-EnvOrMap $EnvMap "JAVA_HOME"
    if ($existing -and (Test-Path -LiteralPath $existing -PathType Container)) {
        return (Resolve-Path $existing).Path
    }
    $java = Get-CommandPath "java"
    if (-not $java) {
        Write-Warning "Java not found (optional). Default BSL language-server MCP needs JDK 17+. docs/prerequisites.md"
        return ""
    }
    $oldEap = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $probe = & java -XshowSettings:properties -version 2>&1 | Select-String "java.home"
    }
    finally {
        $ErrorActionPreference = $oldEap
    }
    $detected = ""
    if ($probe) {
        $javaHomeDir = ($probe.ToString() -split "=", 2)[1].Trim()
        if (Test-Path -LiteralPath $javaHomeDir -PathType Container) {
            $detected = $javaHomeDir
        }
    }
    if ($NonInteractive -or -not $detected) {
        return $detected
    }
    Write-Hint ""
    Write-Hint "JAVA_HOME нужен штатному MCP bsl-language-server (анализ BSL). Можно оставить пустым, если свой MCP без Java."
    Write-Hint "Обнаружен Java home: $detected"
    return Read-Default "Путь JAVA_HOME" $detected
}

function Get-ConveyorAgents {
    return @(
        @{ Id = "1c-analyst"; Skills = @("workspace", "platform_help", "conf_docs", "code_index", "local_research", "web_search") },
        @{ Id = "1c-yaxunit"; Skills = @("workspace", "yaxunit_docs", "platform_help", "code_index", "bsl_lint", "local_research", "web_search") },
        @{ Id = "1c-coder"; Skills = @("workspace", "platform_help", "code_index", "bsl_lint", "local_research") },
        @{ Id = "1c-implementer"; Skills = @("workspace", "platform_help", "code_index", "local_research", "bsl_lint") }
    )
}

function Invoke-KbshffProvider([string]$Kbshff, [string]$ProjectRoot, [string]$AgentId, [string[]]$ExpectedSkills, [string]$ProvBaseUrl, [string]$ProvModel, [string]$ProvKeyEnv, [string]$StepLabel = "") {
    $title = "kbshff CLI: init / import skills / provider set / check ($AgentId)"
    if ($StepLabel) {
        $title = "$StepLabel $title"
    }
    Write-Step $title
    New-Item -ItemType Directory -Force -Path $ProjectRoot | Out-Null
    Invoke-NativeProcess -FilePath $Kbshff -ArgumentList @("init", $AgentId, "--project-root", $ProjectRoot, "--force") -FailMessage "kbshff init $AgentId failed"
    $staging = Join-Path $ProjectRoot ".kuibysheff\.1c-live-import\$AgentId"
    if (Test-Path -LiteralPath $staging) {
        Remove-Item -LiteralPath $staging -Recurse -Force
    }
    New-Item -ItemType Directory -Force -Path $staging | Out-Null
    $settings = Join-Path $RepoRoot "profiles\$AgentId"
    foreach ($name in @("master_prompt.md", "skills.dsl", "rules.md")) {
        $src = Join-Path $settings $name
        if (-not (Test-Path -LiteralPath $src -PathType Leaf)) {
            throw "missing $src - conveyor profile $AgentId is incomplete"
        }
        Copy-Item -LiteralPath $src -Destination (Join-Path $staging $name) -Force
    }
    Invoke-NativeProcess -FilePath $Kbshff -ArgumentList @("config", "--project-root", $ProjectRoot, "--agent", $AgentId, "import", "--from", $staging, "--force") -FailMessage "kbshff config import $AgentId failed"
    Invoke-NativeProcess -FilePath $Kbshff -ArgumentList @("config", "--project-root", $ProjectRoot, "--agent", $AgentId, "provider", "set", "--base-url", $ProvBaseUrl, "--model", $ProvModel, "--api-key-env", $ProvKeyEnv) -FailMessage "kbshff config provider set $AgentId failed"
    $listed = Invoke-NativeProcess -FilePath $Kbshff -ArgumentList @("config", "--project-root", $ProjectRoot, "--agent", $AgentId, "--format", "json", "skill", "list") -FailMessage "kbshff config skill list $AgentId failed" -CaptureOutput
    $listedText = ($listed | Out-String)
    foreach ($skill in $ExpectedSkills) {
        if ($listedText -notmatch [regex]::Escape($skill)) {
            throw "skill '$skill' missing after import of $AgentId. skill list: $listedText"
        }
    }
    Write-Host "OK  $AgentId skills: $($ExpectedSkills -join ', ')"
    Invoke-NativeProcess -FilePath $Kbshff -ArgumentList @("check", "--project-root", $ProjectRoot, "--agent", $AgentId, "--skip-mcp", "--skip-sandbox") -FailMessage "kbshff check $AgentId failed"
}

function Install-ConveyorProfiles([string]$Kbshff, [string]$ProjectRoot, [string]$ProvBaseUrl, [hashtable]$ProvModels, [string]$ProvKeyEnv) {
    Write-Step "Conveyor profiles (all skills)"
    $agents = Get-ConveyorAgents
    $total = $agents.Count
    $i = 0
    foreach ($agent in $agents) {
        $i++
        $model = [string]$ProvModels[$agent.Id]
        if ([string]::IsNullOrWhiteSpace($model)) {
            throw "model for agent $($agent.Id) is empty"
        }
        Invoke-KbshffProvider $Kbshff $ProjectRoot $agent.Id $agent.Skills $ProvBaseUrl $model $ProvKeyEnv "[$i/$total]"
    }
}

function Read-ProviderSettings([hashtable]$EnvMap) {
    Write-Step "AI provider"
    if (-not $NonInteractive) {
        Write-Host ""
        Write-Host "Нужен любой OpenAI-compatible HTTP API (Chat Completions)."
        Write-Host "Эндпоинт (base_url) и ключ - общие; модель задаётся отдельно для каждого агента конвейера."
        Write-Host "Параметры попадут в kbshff через: config provider set --base-url --model --api-key-env"
        Write-Host "Сам ключ хранится только в .env / окружении и НЕ передаётся в argv CLI."
        Write-Host "Значения по умолчанию - плейсхолдеры формата, не рекомендация конкретного вендора."
        Write-Host ""
    }
    if (-not $script:BaseUrl) {
        $script:BaseUrl = Get-EnvOrMap $EnvMap "KBSHFF_PROVIDER_BASE_URL"
        if (-not $script:BaseUrl) { $script:BaseUrl = "https://api.openai.com/v1" }
        Write-Hint "base_url - общий URL эндпоинта до /v1 для всех агентов."
        Write-Hint "Пример формата: https://api.example.com/v1"
        $script:BaseUrl = Read-Default "URL эндпоинта (base_url)" $script:BaseUrl
    }
    $pastedApiKey = ""
    if (-not $script:ApiKeyEnvName) {
        $script:ApiKeyEnvName = Get-EnvOrMap $EnvMap "KBSHFF_PROVIDER_API_KEY_ENV"
        if (-not $script:ApiKeyEnvName) { $script:ApiKeyEnvName = "OPENAI_API_KEY" }
        Write-Hint ""
        Write-Hint "Имя переменной окружения для API-ключа (не сам ключ)."
        Write-Hint "Пример: OPENAI_API_KEY. Сам ключ спросим следующим шагом (ввод скрыт)."
        Write-Hint "kbshff читает секрет из env с этим именем."
        $rawEnvName = Read-Default "Имя переменной для API-ключа" $script:ApiKeyEnvName
        if (Test-LooksLikeApiKey $rawEnvName) {
            Write-Warning "Похоже, вы вставили сам API-ключ вместо имени переменной. Ключ сохраним как секрет; имя env = OPENAI_API_KEY."
            $pastedApiKey = $rawEnvName
            $script:ApiKeyEnvName = "OPENAI_API_KEY"
            $script:ApiKeyEnvName = Read-Default "Имя переменной для API-ключа" $script:ApiKeyEnvName
        }
        else {
            $script:ApiKeyEnvName = $rawEnvName
        }
        if (-not (Test-ValidEnvVarName $script:ApiKeyEnvName)) {
            throw "Invalid API key env var name '$($script:ApiKeyEnvName)'. Use something like OPENAI_API_KEY (letters, digits, underscore)."
        }
    }
    $apiKey = $pastedApiKey
    if (-not $apiKey) {
        $apiKey = Get-EnvOrMap $EnvMap $script:ApiKeyEnvName
    }
    if (-not $apiKey) {
        $apiKey = [Environment]::GetEnvironmentVariable($script:ApiKeyEnvName, "Process")
    }
    if (-not $apiKey) {
        Write-Hint ""
        Write-Hint "Значение ключа для переменной $($script:ApiKeyEnvName)."
        Write-Hint "Ввод скрыт (символы не видны). Вставьте ключ и нажмите Enter."
        for ($attempt = 1; $attempt -le 3; $attempt++) {
            $apiKey = Read-Secret "Значение API-ключа ($($script:ApiKeyEnvName))"
            if (-not [string]::IsNullOrWhiteSpace($apiKey)) {
                break
            }
            Write-Warning "Пустой ввод (попытка $attempt/3). Вставьте ключ ещё раз - символы не отображаются."
        }
    }
    if ([string]::IsNullOrWhiteSpace($apiKey)) {
        throw "API key for $($script:ApiKeyEnvName) is required (set env, .env, or enter it interactively)"
    }
    [Environment]::SetEnvironmentVariable($script:ApiKeyEnvName, $apiKey, "Process")

    $defaultModel = $script:Model
    if (-not $defaultModel) {
        $defaultModel = Get-EnvOrMap $EnvMap "KBSHFF_PROVIDER_MODEL"
    }
    if (-not $defaultModel) {
        $defaultModel = "gpt-4o"
    }
    $script:Model = $defaultModel

    $cliByAgent = @{
        "1c-analyst"     = $script:ModelAnalyst
        "1c-yaxunit"     = $script:ModelYaxunit
        "1c-coder"       = $script:ModelCoder
        "1c-implementer" = $script:ModelImplementer
    }
    Write-Hint ""
    Write-Hint "model - id модели у провайдера. Один эндпоинт, но модель можно выбрать разной для каждой стадии."
    Write-Hint "Плейсхолдер формата: gpt-4o (Enter - принять значение в скобках)."
    $script:AgentModels = @{}
    foreach ($agent in (Get-ConveyorAgents)) {
        $envName = Get-AgentModelEnvName $agent.Id
        $chosen = [string]$cliByAgent[$agent.Id]
        if (-not $chosen) {
            $chosen = Get-EnvOrMap $EnvMap $envName
        }
        if (-not $chosen) {
            $chosen = $defaultModel
        }
        $chosen = Read-Default "Модель для $($agent.Id)" $chosen
        if ([string]::IsNullOrWhiteSpace($chosen)) {
            throw "model for $($agent.Id) is required"
        }
        $script:AgentModels[$agent.Id] = $chosen
    }
    return $apiKey
}

# --- main ---

New-Item -ItemType Directory -Force -Path $ToolsDir | Out-Null

Write-Step "Host tools"
Require-HostTool "git" "https://git-scm.com/ - see docs/prerequisites.md"
$oscriptBin = Ensure-Oscript
$optionalGaps = New-Object System.Collections.Generic.List[string]
if (Test-Command "node") {
    Write-Host "OK  node (recommended for BSL LS MCP)"
}
else {
    $optionalGaps.Add("Node.js (LTS) + npm - штатный tools/bsl-ls-mcp. https://nodejs.org/  (docs/prerequisites.md)")
}
if (Test-Command "java") {
    Write-Host "OK  java (recommended for BSL LS JAR, JDK 17+)"
}
else {
    $optionalGaps.Add("Java / JDK 17+ - запуск bsl-language-server JAR. https://adoptium.net/  (docs/prerequisites.md)")
}
$pythonCmd = Find-Python
if ($pythonCmd.Count -eq 0) {
    throw "Python 3 not found (py / python / python3). Needed for 1c-sntx-sem. docs/prerequisites.md"
}
Write-Host "OK  python ($($pythonCmd -join ' '))"
if (-not $SkipIngest -and -not $PlatformPath) {
    $platformBins = @(Find-1cPlatformBins)
    if ($platformBins.Count -eq 0) {
        $optionalGaps.Add("Платформа 1С (каталог bin 8.3.* с 1cv8/ibcmd) - для ingest sntx_sem. Либо укажите -PlatformPath, либо -SkipIngest.")
    }
    else {
        Write-Host "OK  1C platform bin (found $($platformBins.Count))"
    }
}
Confirm-OptionalHostGaps @($optionalGaps)

$envPath = Join-Path $RepoRoot ".env"
$envMap = Read-DotEnv $envPath

$apiKey = Read-ProviderSettings $envMap

$kbshff = Ensure-Kbshff $envMap
$indexer = Ensure-BslIndexer $envMap
$mcpJs = Ensure-BslLsMcp $envMap
$jar = ""
if ($mcpJs) {
    $jar = Ensure-BslLsJar $envMap
}
elseif (Get-EnvOrMap $envMap "BSL_LS_JAR") {
    $jar = Ensure-BslLsJar $envMap
}
else {
    Write-Host "Skipping BSL LS JAR (no bsl-ls-mcp path). Set BSL_LS_MCP / install Node, or use your own MCP."
}
$sntx = Ensure-SntxSem $envMap $pythonCmd
$javaHome = ""
if ($jar -or $mcpJs) {
    $javaHome = Resolve-JavaHome $envMap
}

$envMap["KBSHFF_PROVIDER_BASE_URL"] = $BaseUrl
$envMap["KBSHFF_PROVIDER_MODEL"] = $Model
$envMap["KBSHFF_PROVIDER_API_KEY_ENV"] = $ApiKeyEnvName
$envMap[$ApiKeyEnvName] = $apiKey
foreach ($agent in (Get-ConveyorAgents)) {
    $envName = Get-AgentModelEnvName $agent.Id
    $envMap[$envName] = [string]$script:AgentModels[$agent.Id]
}
$envMap["SNTX_SEM_CONFIG"] = $sntx.Config
$envMap["SNTX_SEM_PYTHON"] = $sntx.Python
$envMap["BSL_INDEXER"] = $indexer
$envMap["CODE_INDEX_HOME"] = Split-Path -Parent $indexer
if ($mcpJs) { $envMap["BSL_LS_MCP"] = $mcpJs } else { $envMap.Remove("BSL_LS_MCP") }
if ($jar) { $envMap["BSL_LS_JAR"] = $jar } else { $envMap.Remove("BSL_LS_JAR") }
$envMap["KBSHFF_BIN"] = $kbshff
$envMap["OSCRIPT_BIN"] = $oscriptBin
if ($javaHome) {
    $envMap["JAVA_HOME"] = $javaHome
    [Environment]::SetEnvironmentVariable("JAVA_HOME", $javaHome, "Process")
}
$exportNames = @(
    "KBSHFF_PROVIDER_BASE_URL", "KBSHFF_PROVIDER_MODEL",
    "KBSHFF_PROVIDER_MODEL_1C_ANALYST", "KBSHFF_PROVIDER_MODEL_1C_YAXUNIT",
    "KBSHFF_PROVIDER_MODEL_1C_CODER", "KBSHFF_PROVIDER_MODEL_1C_IMPLEMENTER",
    "KBSHFF_PROVIDER_API_KEY_ENV", "SNTX_SEM_CONFIG", "SNTX_SEM_PYTHON",
    "BSL_INDEXER", "KBSHFF_BIN", "OSCRIPT_BIN"
)
foreach ($name in $exportNames) {
    [Environment]::SetEnvironmentVariable($name, $envMap[$name], "Process")
}
if ($mcpJs) { [Environment]::SetEnvironmentVariable("BSL_LS_MCP", $mcpJs, "Process") }
if ($jar) { [Environment]::SetEnvironmentVariable("BSL_LS_JAR", $jar, "Process") }

Save-DotEnv $envPath $envMap
Write-Host "Wrote $envPath"

Install-ConveyorProfiles $kbshff $RepoRoot $BaseUrl $script:AgentModels $ApiKeyEnvName

Write-Step "harness dry-run"
Invoke-NativeProcess -FilePath $oscriptBin -ArgumentList @("-encoding=utf-8", (Join-Path $RepoRoot "harness\run.os"), "--repo-root", $RepoRoot, "--dry-run") -FailMessage "dry-run failed"

Write-Host ""
Write-Host "Install OK. Conveyor is ready."
Write-Host "Profiles with skills: 1c-analyst, 1c-yaxunit, 1c-coder, 1c-implementer"
Write-Host "Live eval:  .\harness\run.cmd"
Write-Host "Howto:      docs\howto-pipeline.md"
Write-Host "CLI help:   kbshff help config"
exit 0
